### ISSUE TITLE
Consider using simple-http-server instead of miniserve

### ISSUE THREAD

**Issue by siku2** [L117/yew-min-wbg#1]
[miniserve](https://github.com/svenstaro/miniserve) is a great http server but it has a few shortcomings when it comes to this particular use case.
Specifically, miniserve can't be used to host single-page applications (yet?) so it can't be used with [yew-router](https://yew.rs/docs/concepts/router).

I found an alternative, [simple-http-server](https://github.com/TheWaWaR/simple-http-server), which accepts the argument `--try-file` which can be used exactly for this purpose.
The following command starts the server with what I found to be the most appropriate settings.
```bash
simple-http-server \
        --index --nocache \
        --try-file "dist/index.html" \
        dist
```

**Comment by L117** [comment]
Sure. This makes sense.

**Comment by ucyo** [comment]
I just stumbled upon this and it fixed my issue. But what is the specific reason miniserve fails? Some kind of url solving issue?
